executable = /bin/singularity
args = "exec \
--bind /data/bioinfo/common/bowtie2_index_v37:/nfs/pic.es/user/r/rgomez/20210325_breakseq/data/use/bowtie_index \
--bind /data/bioinfo/scratch/breakseq_tmp/:/nfs/pic.es/user/r/rgomez/20210325_breakseq/tmp/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/:rw \
/data/bioinfo/software/rgomez_breakseq.sif \
bash 20210325_breakseq/runall.sh processaligned -a analysis/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/02_breakseq/ -s analysis/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/data/samples.txt -m $(Item) -t min_20_$(Item) -n 2022-10-14_1kgp_phase3_static_v2.4.1.300_v37"

output = analysis/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/log/03_processaligned/condor.out
error = analysis/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/log/03_processaligned/condor.err
log = analysis/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/log/03_processaligned/condor.log

request_cpus = 1

queue 1 in (30) 
