executable = /bin/singularity
args = "exec \
--bind /data/bioinfo/scratch/breakseq_tmp/:/nfs/pic.es/user/r/rgomez/20210325_breakseq/tmp/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/:rw \
/data/bioinfo/software/rgomez_plots.sif \
bash 20210325_breakseq/runall.sh qualityanalysis \
-g analysis/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/03_processaligned/ -s analysis/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/data/samples.txt -r analysis/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/data/regions.txt -m 0.03 -t min_20_30 -n 2022-10-14_1kgp_phase3_static_v2.4.1.300_v37"

output = analysis/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/log/04_qualityanalysis/condor.out
error = analysis/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/log/04_qualityanalysis/condor.err
log = analysis/2022-10-14_1kgp_phase3_static_v2.4.1.300_v37/log/04_qualityanalysis/condor.log

request_cpus = 1

queue 1
