executable = /bin/singularity
args = "exec \
--bind /data/bioinfo/scratch/breakseq_fastqs/01_download/2021-05-07/:/nfs/pic.es/user/r/rgomez/20210325_breakseq/analysis/2021-07-22_library.v2.3.2/01_download/:rw \
--bind /data/bioinfo/common/bowtie2_index:/nfs/pic.es/user/r/rgomez/20210325_breakseq/data/use/bowtie_index \
--bind /data/bioinfo/scratch/breakseq_tmp/:/nfs/pic.es/user/r/rgomez/20210325_breakseq/tmp/2021-07-22_library.v2.3.2/:rw \
/data/bioinfo/software/rgomez_breakseq.sif \
bash 20210325_breakseq/runall.sh breakseq -m 20 -l 300 -f analysis/2021-07-22_library.v2.3.2/01_download/ -s $(Item) -t $(Item) -n 2021-07-22_library.v2.3.2"

output = analysis/2021-07-22_library.v2.3.2/log/02_breakseq/condor.out
error = analysis/2021-07-22_library.v2.3.2/log/02_breakseq/condor.err
log = analysis/2021-07-22_library.v2.3.2/log/02_breakseq/condor.log

request_cpus = 1

queue 1 from tmp/2021-07-22_library.v2.3.2/02_breakseq/failednames 
