executable = /bin/singularity
args = "exec \
--bind /data/bioinfo/common/bowtie2_index:/nfs/pic.es/user/r/rgomez/20210325_breakseq/data/use/bowtie_index \
--bind /data/bioinfo/scratch/breakseq_tmp/:/nfs/pic.es/user/r/rgomez/20210325_breakseq/tmp/2021-07-22_library.v2.3.2/:rw \
/data/bioinfo/software/rgomez_breakseq.sif \
bash 20210325_breakseq/runall.sh processaligned -a analysis/2021-07-22_library.v2.3.2/02_breakseq/ -s analysis/2021-07-22_library.v2.3.2/data/samples.txt -m $(Item) -t min_20_$(Item) -n 2021-07-22_library.v2.3.2"

output = analysis/2021-07-22_library.v2.3.2/log/03_processaligned/condor.out
error = analysis/2021-07-22_library.v2.3.2/log/03_processaligned/condor.err
log = analysis/2021-07-22_library.v2.3.2/log/03_processaligned/condor.log

request_cpus = 1

queue 1 in (30) 
