executable = /bin/singularity
args = "exec \
--bind /data/bioinfo/scratch/breakseq_fastqs:/nfs/pic.es/user/r/rgomez/20210325_breakseq/analysis/2021-09-20_v2.3.2_downloadReadsCheck/01_download/:rw \
/data/bioinfo/software/rgomez_breakseq.sif \
bash 20210325_breakseq/runall.sh download -r analysis/2021-09-20_v2.3.2_downloadReadsCheck/data/regions.txt -s $(item) -t $(item) -n 2021-09-20_v2.3.2_downloadReadsCheck"

output = analysis/2021-09-20_v2.3.2_downloadReadsCheck/log/01_download/condor.out
error = analysis/2021-09-20_v2.3.2_downloadReadsCheck/log/01_download/condor.err
log = analysis/2021-09-20_v2.3.2_downloadReadsCheck/log/01_download/condor.log

request_cpus = 1

queue 1 from tmp/2021-09-20_v2.3.2_downloadReadsCheck/01_download/failednames
