executable = /bin/singularity
args = "exec \
--bind /data/bioinfo/scratch/breakseq_fastqs/2022-07-08_half2kgp_v2.3.3.300/:/nfs/pic.es/user/r/rgomez/20210325_breakseq/analysis/2022-07-08_half2kgp_v2.3.3.300/01_download/:rw \
--bind /data/bioinfo/common/bowtie2_index:/nfs/pic.es/user/r/rgomez/20210325_breakseq/data/use/bowtie_index \
--bind /data/bioinfo/scratch/breakseq_tmp/:/nfs/pic.es/user/r/rgomez/20210325_breakseq/tmp/2022-07-08_half2kgp_v2.3.3.300/:rw \
/data/bioinfo/software/rgomez_breakseq.sif \
bash 20210325_breakseq/runall.sh breakseq -k L,0,-0.3 -m 20 -l 300 -f analysis/2022-07-08_half2kgp_v2.3.3.300/01_download/ -s $(Item) -t $(Item) -n 2022-07-08_half2kgp_v2.3.3.300"

output = analysis/2022-07-08_half2kgp_v2.3.3.300/log/02_breakseq/condor.out
error = analysis/2022-07-08_half2kgp_v2.3.3.300/log/02_breakseq/condor.err
log = analysis/2022-07-08_half2kgp_v2.3.3.300/log/02_breakseq/condor.log

request_cpus = 1

queue 1 from tmp/2022-07-08_half2kgp_v2.3.3.300/02_breakseq/failednames 
