executable = /bin/singularity
args = "exec \
--bind /data/bioinfo/scratch/breakseq_fastqs:/nfs/pic.es/user/r/rgomez/20210325_breakseq/analysis/2022-10-03_avery_v2.3.3.300/01_download/:rw \
/data/bioinfo/software/sratoolkit.2.11.3_latest.sif  \
bash 20210325_breakseq/code/bash/01_downloadSRA.sh data/raw/avery_data/prj_21579.ngc $(item) analysis/2022-10-03_avery_v2.3.3.300/01_download/2022-09-30_SRA_avery"

output = analysis/2022-10-03_avery_v2.3.3.300/log/01_download/condor.out
error = analysis/2022-10-03_avery_v2.3.3.300/log/01_download/condor.err
log = analysis/2022-10-03_avery_v2.3.3.300/log/01_download/condor.log

request_cpus = 1

queue 1 from analysis/2022-10-03_avery_v2.3.3.300/data/sra_download.txt
