executable = /bin/singularity
args = "exec \
--bind /data/bioinfo/scratch/breakseq_fastqs:/nfs/pic.es/user/r/rgomez/20210325_breakseq/analysis/2022-10-20_1kgp_highcov_static_v2.4.1.300_v38/01_download/:rw \
--bind /data/bioinfo/scratch/breakseq_bam:/nfs/pic.es/user/r/rgomez/20210325_breakseq/analysis/2022-10-20_1kgp_highcov_static_v2.4.1.300_v38/data/bamFiles/:rw \
/data/bioinfo/software/rgomez_breakseq.sif \
bash 20210325_breakseq/runall.sh download -r tmp/2022-10-20_1kgp_highcov_static_v2.4.1.300_v38/01_download/failedcases -s '$(item)' -t '$(item)' -n 2022-10-20_1kgp_highcov_static_v2.4.1.300_v38"

output = analysis/2022-10-20_1kgp_highcov_static_v2.4.1.300_v38/log/01_download/condor.out
error = analysis/2022-10-20_1kgp_highcov_static_v2.4.1.300_v38/log/01_download/condor.err
log = analysis/2022-10-20_1kgp_highcov_static_v2.4.1.300_v38/log/01_download/condor.log

request_cpus = 1

queue 1 from tmp/2022-10-20_1kgp_highcov_static_v2.4.1.300_v38/01_download/failednames
