executable = /bin/singularity
args = "exec \
--bind /data/bioinfo/common/bowtie2_index_v38:/nfs/pic.es/user/r/rgomez/20210325_breakseq/data/use/bowtie_index:rw \
--bind /data/bioinfo/scratch/breakseq_tmp/:/nfs/pic.es/user/r/rgomez/20210325_breakseq/tmp/2022-11-29_1kgp_30x_only133.300_v38/:rw \
/data/bioinfo/software/rgomez_plots.sif \
Rscript 20210325_breakseq/code/rscript/05_tagsnps.R 20210325_breakseq/analysis/2022-11-29_1kgp_30x_only133.300_v38/05_tagsnps/tagSNPs_max.txt 20210325_breakseq/analysis/2022-11-29_1kgp_30x_only133.300_v38/05_tagsnps/  "

output = analysis/2022-11-29_1kgp_30x_only133.300_v38/log/05_tagsnps_plot/condor.out
error = analysis/2022-11-29_1kgp_30x_only133.300_v38/log/05_tagsnps_plot/condor.err
log = analysis/2022-11-29_1kgp_30x_only133.300_v38/log/05_tagsnps_plot/condor.log

request_cpus = 1

queue 1 
