executable = /bin/singularity
args = "exec \
--bind /data/bioinfo/scratch/1KGP_hg19_raw/:/nfs/pic.es/user/r/rgomez/20210325_breakseq/data/raw/1KGP_data/vcf \
--bind /data/bioinfo/scratch/breakseq_tmp/:/nfs/pic.es/user/r/rgomez/20210325_breakseq/tmp/2022-04-18_agdp/:rw \
/data/bioinfo/software/rgomez_plots.sif \
bash 20210325_breakseq/runall.sh qualityanalysis \
-g analysis/2022-04-18_agdp/03_processaligned/ -s analysis/2022-04-18_agdp/data/samples.txt -r analysis/2022-04-18_agdp/data/regions.txt -m 0.03 -t min_10_20 -n 2022-04-18_agdp"

output = analysis/2022-04-18_agdp/log/04_qualityanalysis/condor.out
error = analysis/2022-04-18_agdp/log/04_qualityanalysis/condor.err
log = analysis/2022-04-18_agdp/log/04_qualityanalysis/condor.log

request_cpus = 1

queue 1
